set $bg #282828
set $red #cc241d
set $green #98971a
set $yellow #d79921
set $blue #458588
set $purple #b16286
set $aqua #689d68
set $gray #a89984
set $darkgray #1d2021
set $lightgray #bdae93
set $white #ffffff
set $window_focused_bg #32302f
set $window_inactive_bg #1b1b1b

# class                 border               backgr               text        indicator  child_border
client.focused          $window_focused_bg   $window_focused_bg   $lightgray  $purple    $darkgray
client.focused_inactive $window_inactive_bg  $window_inactive_bg  $lightgray  $purple    $darkgray
client.unfocused        $window_inactive_bg  $window_inactive_bg  $lightgray  $purple    $darkgray
client.urgent           $red                 $red                 $white      $red       $red

bar {
    status_command i3blocks -c ~/.config/i3/i3blocks.conf
    tray_output primary
    position top
    colors {
        background $bg
        statusline $lightgray
        #                    border     backgr.    text
        focused_workspace    $lightgray $lightgray $bg
        inactive_workspace   $darkgray  $darkgray  $lightgray
        active_workspace     $darkgray  $darkgray  $lightgray
        urgent_workspace     $red       $red       $bg
    }
}

# vim:ft=i3config
