set $bg #fbf1c7
set $red #cc241d
set $green #79740e
set $yellow #b57614
set $blue #076678
set $purple #8f3f71
set $aqua #427b58
set $gray #7c6f64
set $darkgray #ebdbb2
set $lightgray #3c3836
set $white #fbf1c7
set $window_focused_bg #d5c4a1
set $window_inactive_bg #ebdbb2
