#!/bin/sh

existing_files=".bash_logout .bashrc .bash_profile"

for file in ${existing_files}; do
  path="$HOME/$file"
  # rename old files only if they are not links
  [ -f "$path" ] && [ ! -L "$path" ] && mv "$path" "$HOME/$file-old"
done

Darwin="bash git nvim lf scripts vim alacritty newsboat archive/macos/skhd archive/macos/spacebar archive/macos/yabai"

Linux="bash zsh git nvim lf scripts vim alacritty newsboat bottom npm awesome rofi touchegg picom mpv xorg udiskie"

currentdir=$(pwd)

if [ "$(uname)" = "Darwin" ]; then
  dirs=${Darwin}
elif [ "$(uname)" = "Linux" ]; then
  dirs=${Linux}
fi

for dir in ${dirs}; do
  dirname="$(dirname "$dir")"
  pkgname="$(basename "$dir")"

  cd "$dirname" || exit 1

  stow -v --target="$HOME" "$pkgname"

  cd "$currentdir" || exit 1
done
