#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

init() {
  echo "Initializing submodules..."
  git submodule init
  git submodule update

  echo "Cloning public repo..."
  git clone git@github.com:sarmong/dotfiles.git "$XDG_SRC_DIR/dotfiles-public"

  echo "Adding hooks..."
  git config --local core.hooksPath .gitconfig/hooks

  echo "Done."
}

update() {
  git stash
  git pull
  make ansible
}

ansible() {
  scripts/ansible.sh "$@"
}

ansible-check() {
  scripts/ansible.sh --check "$@"
}

sync-public() {
  scripts/sync-repos.sh
}

"$@"
