#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

init() {
  echo "Initializing submodules..."
  git submodule init
  git submodule update

  echo "Installing tmux plugins"
  ./dotconfig/tmux/plugins/tpm/scripts/install_plugins.sh
  echo "Done."
}

update() {
  git stash
  git pull
  make ansible
}

ansible() {
  scripts/ansible.sh "$@"
}

ansible-check() {
  scripts/ansible.sh --check "$@"
}

"$@"
