# vim:ft=yaml.ansible

- name: Configure keyd
  become: true
  block:
    - name: keyd | check packages
      pacstall:
        name: keyd

    # or link?? ( I do link now )
    - name: keyd | copy config file
      copy:
        src: ~/.local/bin/services/keyd/default.conf
        dest: /etc/keyd/default.conf
        mode: preserve
      when: ansible_hostname != 'air'

    - name: keyd | copy mac config file
      copy:
        src: ~/.local/bin/services/keyd/mac.conf
        dest: /etc/keyd/default.conf
        mode: preserve
      when: ansible_hostname == 'air'

    - name: keyd | enable service
      systemd_service:
        state: started
        enabled: true
        name: keyd
