- name: Configure keyd
  become: true
  block:
    - name: keyd | check packages
      pacstall:
        name: keyd

    - name: keyd | copy config file
      copy:
        src: keyd-default.conf
        dest: /etc/keyd/default.conf
        mode: preserve
      when: ansible_hostname != 'air'
      register: keyd_conf

    - name: keyd | copy mac config file
      copy:
        src: keyd-mac.conf
        dest: /etc/keyd/default.conf
        mode: preserve
      when: ansible_hostname == 'air'
      register: keyd_conf

    - name: keyd | enable service
      systemd_service:
        state: started
        enabled: true
        name: keyd

    - name: keyd | restart service
      systemd_service:
        state: restarted
        name: keyd
      when: keyd_conf.changed
