# vim:ft=yaml.ansible

- name: Configure lightdm
  become: true
  block:
    - name: lightdm | packages
      apt:
        state: present
        name:
          - lightdm
          - lightdm-gtk-greeter

    - name: lightdm | copy config files
      copy:
        src: "{{ item }}"
        dest: /etc/lightdm/"{{ item | basename }}"
        mode: preserve
      loop:
        - lightdm/lightdm.conf
        - lightdm/lightdm-gtk-greeter.conf
        # s/lightdm/slick-greeter.conf
        - lightdm/wp.jpg
        - lightdm/Xsession

    - name: lightdm | enable service
      systemd_service:
        state: started
        enabled: true
        name: lightdm
