- name: sudoers.d configuration
  become: true
  copy:
    src: "sudoers/{{ item }}"
    dest: "/etc/sudoers.d/{{ item }}"
    validate: /usr/sbin/visudo -csf %s
    owner: root
    group: root
    mode: "0440"
  loop:
    - admin-flag
    - tty-tickets
    - visudo-editor
