---
- name: create swap
  become: true
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Check if /swap.img is active
      command: grep -q '/swap.img' /proc/swaps
      register: swap_img_active
      failed_when: false
      changed_when: false

    - name: Disable /swap.img if active
      command: swapoff /swap.img
      when: swap_img_active.rc == 0
      changed_when: swap_img_active.rc == 0

    - name: Remove /swap.img file
      file:
        path: /swap.img
        state: absent

    - name: Remove /swap.img from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '.*swap\.img.*'
        state: absent

    - name: Create 40GB swapfile
      command: fallocate -l 40G /swapfile
      args:
        creates: /swapfile

    - name: Set correct permissions on swapfile
      file:
        path: /swapfile
        owner: root
        group: root
        mode: "0600"

    - name: Check if /swapfile is already active
      ansible.builtin.command: grep -q '/swapfile' /proc/swaps
      register: swapfile_active
      failed_when: false
      changed_when: false

    - name: Format swapfile
      ansible.builtin.command: mkswap /swapfile
      when: swapfile_active.rc != 0
      changed_when: swapfile_active.rc != 0

    - name: Enable swapfile
      ansible.builtin.command: swapon /swapfile
      when: swapfile_active.rc != 0
      changed_when: swapfile_active.rc != 0

    - name: Add swapfile to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "/swapfile   none   swap   sw   0   0"
        regexp: ".*swapfile.*"
        state: present
