- name: Configure ufw
  become: true
  tags:
    - ufw
  block:
    - name: ufw | packages
      apt:
        state: present
        name: ufw

    - name: ufw | deny all trafic
      ufw:
        policy: deny

    - name: ufw | allow stuff
      ufw:
        name: "{{ item }}"
        rule: allow
      loop:
        - qbittorrent
        - syncthing
      when: ansible_connection == "local"

    - name: ufw | allow local network
      ufw:
        src: 192.168.0.0/24
        rule: allow
      when: ansible_connection == "local"

    - name: ufw | limit ssh
      ufw:
        rule: limit
        port: ssh
        proto: tcp
        src: 192.168.0.0/24
      when: ansible_connection == "local"

    - name: ufw | allow ssh and nginx
      ufw:
        name: "{{ item }}"
        rule: allow
      loop:
        - OpenSSH
      when: group_names[0] == "vps"

    - name: ufw | allow http ports
      ufw:
        rule: allow
        port: "80,443"
        proto: tcp
      when: group_names[0] == "vps"

    - name: ufw | enable ufw
      ufw:
        state: enabled

    - name: ufw | enable ufw service
      systemd_service:
        state: started
        enabled: true
        name: ufw
