---
- name: Install navidrome
  tags:
    - apm
  include_tasks: tasks/software/apm/main.yml
  loop:
    - navidrome

- name: Copy config
  become: true
  copy:
    src: navidrome.toml
    dest: /etc/navidrome/navidrome.toml
    mode: preserve
  register: config_update

- name: enable service
  become: true
  systemd_service:
    name: navidrome
    enabled: true
    state: started

- name: navidrome | restart service
  become: true
  systemd_service:
    state: restarted
    name: navidrome
  when: config_update.changed
