---
- name: install caddy
  become: true
  block:
    - name: Install dependencies
      package:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl
        state: present

    - name: Ensure directory exists for /usr/share/keyrings
      file:
        path: /usr/share/keyrings
        state: directory
        mode: "0755"

    - name: Add Caddy apt key
      get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        dest: /usr/share/keyrings/caddy-stable-archive-keyring.asc
        mode: "0644"
        checksum: sha256:5791c2fb6b6e82feb5a69834dd2131f4bcc30af0faec37783b2dc1c5c224a82a

    - name: Add Caddy repository
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: caddy-stable
        update_cache: true
      loop:
        - deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.asc]
          https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version
          main
        - deb-src
          [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.asc]
          https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version
          main

    - name: Install caddy
      apt:
        name: caddy
      notify:
        - Restart caddy

- name: Include caddyfiles
  become: true
  copy:
    content: import /etc/caddy/sites/*.caddyfile
    dest: /etc/caddy/Caddyfile
    mode: "0644"
  notify: Restart caddy

- name: Create sites directory
  become: true
  file:
    path: /etc/caddy/sites/
    state: directory
    mode: "0755"
