- name: Create main user
  when: ansible_user != user
  block:
    - name: Check if main user exists
      command: "id -u {{ user }}"
      register: user_check
      ignore_errors: true
      failed_when: false
      changed_when: false

    - name: "Check ansible_user"
      fail:
        msg: "User exists, change user in inventory file"
      when: user_check.rc == 0 and ansible_user != user

    - name: "Get new user password"
      pause:
        prompt: "Enter the password for the new user"
        echo: false
      register: result
      when: user_check.rc == 1
      no_log: true

    - name: "Repeat new user password"
      pause:
        prompt: "Repeat the password: "
        echo: false
      register: result_check
      when: user_check.rc == 1
      no_log: true

    - name: Set password
      set_fact:
        password: "{{ result.user_input }}"
        password_check: "{{ result_check.user_input }}"
      when: user_check.rc == 1
      no_log: true

    - name: Check passwords match
      fail:
        msg: "Passwords don't match"
      when: user_check.rc == 1 and password != password_check

    - name: Create new user
      become: true
      user:
        name: "{{ user }}"
        groups: sudo
        append: true
        password: "{{ password | password_hash('sha512') }}"
      when: user_check.rc == 1

    - name: Install SSH keys
      block:
        - name: Set correct permissions for .ssh directory
          become: true
          file:
            path: "/home/{{ user }}/.ssh"
            state: directory
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "0700"

        - name: Copy SSH keys from root to user
          become: true
          copy:
            src: "{{ ansible_user_dir }}/.ssh/authorized_keys"
            dest: "/home/{{ user }}/.ssh/authorized_keys"
            remote_src: true
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "0600"

      rescue:
        - name: Remove user
          become: true
          user:
            name: "{{ user }}"
            state: absent
        - name: Fail
          fail:
            msg: "Error occured"

    - name: Switch to new user for remaining tasks
      set_fact:
        ansible_user: "{{ user }}"
        ansible_become_password: "{{ password }}"

- name: Update env vars for new user
  when: initial_user != user
  block:
    - name: Refresh environment variables (ansible_env)
      setup:
        gather_subset: env

    - name: Reassign ansible_env after setup
      set_fact:
        ansible_env: "{{ ansible_facts['env'] }}"

    - name: Load xdg variables (with new loaded ansible_env)
      tags: always
      include_vars:
        dir: vars

    - name: Set variables as facts globally
      set_fact:
        remote: "{{ remote }}"

- name: Create ci user
  become: true
  block:
    - name: Create new ci_user
      user:
        name: "{{ ci_user }}"
        shell: /usr/bin/bash

    - name: Copy SSH keys from root to ci_user
      authorized_key:
        user: "{{ ci_user }}"
        key: "{{ lookup('file', '~/.ssh/' ~ ci_key ) }}"

    - name: Add main user to ci group
      user:
        name: "{{ user }}"
        groups: "{{ ci_user }}"
        append: true

    - name: Change /var/www permissions
      file:
        path: /var/www
        state: directory
        mode: "0775"
