- name: Set up docker services
  tags:
    - docker
  vars:
    project_dir: "{{ ci | ternary(docker_conf, '~/docs/apps/' ~ docker_conf) }}"
  block:
    - name: docker | {{ docker_conf }} | Create app dir
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0755"
      when: not ci

    - name: docker | {{ docker_conf }} | add port
      lineinfile:
        path: "tasks/server/files/docker/{{ docker_conf | basename }}/.env"
        create: true
        line: "PORT={{ app_port }}"
        mode: "0644"
      when: app_port is defined
      register: updated_port
      delegate_to: localhost

    - name: docker | {{ docker_conf }} | Deploy docker-compose files
      synchronize:
        archive: false
        src: "tasks/server/files/docker/{{ docker_conf | basename }}/"
        dest: "{{ project_dir }}/"
      register: updated_files

    - name: docker | {{ docker_conf }} | Restart docker
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: restarted
      when: updated_files.changed or updated_port.changed

    - name: docker | {{ docker_conf }} | Start docker
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
