---
- name: install docker packages
  become: true
  block:
    - name: Ensure old versions of Docker are not installed
      package:
        name:
          - docker
          - docker-compose
          - docker.io
          - docker-engine
          - docker-doc
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: Ensure directory exists for /usr/share/keyrings
      file:
        path: /usr/share/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker apt key
      get_url:
        url:
          https://download.docker.com/linux/{{ ansible_distribution | lower
          }}/gpg
        dest: /usr/share/keyrings/docker.asc
        mode: "0644"
        force: false
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

    - name: Add Docker repository
      apt_repository:
        repo:
          "deb [arch=amd64
          signed-by=/usr/share/keyrings/docker.asc]  https://download.docker.com/linux/{{
          ansible_distribution | lower }} {{ ansible_distribution_release }}
          stable"
        state: present
        filename: docker
        update_cache: true

    - name: Install packages
      apt:
        name:
          - "docker-ce"
          - "docker-ce-cli"
          - "docker-ce-rootless-extras"
          - "containerd.io"
          - docker-buildx-plugin
          - docker-compose-plugin
      notify:
        - Restart docker service

    - name: Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      register: added_to_docker_group
      notify: Reset ssh connection

    - name: flush handlers # noqa: no-handler
      ansible.builtin.meta: flush_handlers
      when: added_to_docker_group.changed
