- name: Set up dotfiles
  tags: dotfiles
  block:
    - name: Set correct env vars on login
      tags:
        - dotfiles
        - zsh
      become: true
      blockinfile:
        path: /etc/zsh/zshenv
        block: |
          env_file="$HOME/.config/zsh/zsh-exports"
          [ -f "$env_file" ] && . "$env_file"
          export IS_SERVER=true
          export APPIMAGE_EXTRACT_AND_RUN=1 # to run neovim appimage

    - name: Copy dotfiles
      tags:
        - dotfiles
        - zsh
      synchronize:
        src: "{{ lookup('env', 'XDG_DOTFILES_DIR') }}/dotconfig/"
        dest: "{{ ansible_env.XDG_CONFIG_HOME }}"

    - name: Copy .local/bin
      tags:
        - dotfiles
      synchronize:
        src: "{{ lookup('env', 'XDG_DOTFILES_DIR') }}/dotlocal/bin/"
        dest: "{{ ansible_env.XDG_BIN_DIR }}"

    - name: Use neovim stable
      command:
        cmd: "{{ ansible_env.XDG_BIN_DIR }}/nvvm use stable"
        creates: "{{ ansible_env.XDG_DATA_HOME }}/nvvm/bin/nvim"
