- name: Parse tmux.conf and checkout plugin commits
  tags:
    - tmux
    - tmux-plugins
  block:
    - name: Read tmux.conf
      slurp:
        src: "{{ ansible_env.XDG_CONFIG_HOME }}/tmux/tmux.conf"
      register: tmux_conf

    - name: Extract plugins, owners, and commits
      set_fact:
        plugins: >-
          {{ tmux_conf['content'] | b64decode | regex_findall("set -g @plugin
          '([^/]+)/([^']+)' # (\w+)") }}

    - name: Ensure each plugin is at the specified commit
      ansible.builtin.git:
        repo: "https://github.com/{{ item.0 }}/{{ item.1 }}.git"
        dest: "{{ ansible_env.XDG_CONFIG_HOME }}/tmux/plugins/{{ item.1 }}"
        version: "{{ item.2 }}"
        force: true
      loop: "{{ plugins }}"

## https://github.com/tmux-plugins/tmux-continuum/issues/129
- name: Create tmux.service
  tags:
    - tmux
  copy:
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/systemd/user/tmux.service"
    content: |
      [Unit]
      Description=tmux default session (detached)
      Documentation=man:tmux(1)

      [Service]
      Type=forking
      ExecStart=/usr/local/bin/tmux start-server

      ExecStop={{ XDG_CONFIG_HOME }}/tmux/plugins/tmux-resurrect/scripts/save.sh
      ExecStop=/usr/local/bin/tmux kill-server
      KillMode=control-group

      RestartSec=2
