" Clean up vim files from home directory
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')
set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')
if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

call plug#begin()
Plug 'morhetz/gruvbox'
call plug#end()

color gruvbox
set background=dark

" This is used to make bg not disappear. Taken from kitty #108
let &t_ut=''

" With this option, `:find` command searches recursively in all dirs
set path+=**
set wildmenu

set nocompatible
syntax on

set number
set relativenumber
set ruler

set expandtab
set smartindent
set smarttab
set shiftwidth=2
set tabstop=2

set laststatus=2

set backspace=indent,eol,start

set hidden

set smartcase
set incsearch

nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.
set noerrorbells visualbell t_vb=

set mouse+=a
set showcmd

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

command SudaWrite :execute ':silent w !sudo tee % > /dev/null' | :edit!
