- name: "{{ item }} | Install {{ item }}"
  tags:
    - binary
  vars:
    src_dir: "~/.local/src"
    build_extract_dest:
      "{{ (extract_dest == '') | ternary(src_dir, extract_dest) }}"
  block:
    - name: "{{ item }} | create extract dir"
      file:
        path: "{{ build_extract_dest }}"
        state: directory
        mode: "0755"

    - name: "{{ item }} | extract archive to temp directory"
      unarchive:
        src: "{{ file_path }}"
        dest: "{{ build_extract_dest }}"
        remote_src: true
        mode: "0755"
        list_files: true
      register: unarchive_res

    - name: "{{ item }} | build"
      command: "{{ cmd }}"
      loop: "{{ pkg_spec.build_cmds }}"
      loop_control:
        loop_var: cmd
      args:
        chdir:
          "{{ (extract_dest == '') | ternary(src_dir ~ '/' ~
          unarchive_res.files[0], build_extract_dest) }}"
      when: "pkg_spec.build_cmds is defined"
