- name: "{{ item }} | install"
  vars:
    git_dest: "{{ (extract_dest == '') | ternary(ansible_env.XDG_SRC_DIR ~ '/' ~ pkg_spec.name ~ '-' ~ pkg_spec.version, extract_dest) }}"
  block:
    - name: "{{ item }} | clone git repo"
      git:
        repo: "{{ pkg_spec.url }}"
        dest: "{{ git_dest }}"
        version: "{{ pkg_spec.version }}"
        recursive: true

    - name: "{{ item }} | build"
      command: "{{ cmd | regex_replace('^sudo ', '') }}"
      become: "{{ cmd.startswith('sudo ') }}"
      loop: "{{ pkg_spec.build_cmds }}"
      loop_control:
        loop_var: cmd
      args:
        chdir: "{{ git_dest }}"
      when: pkg_spec.build_cmds is defined
