- name: kitty | link binaries
  become: true
  file:
    src: "{{ extract_dest }}/bin/{{ file }}"
    dest: "/usr/local/bin/{{ file }}"
    state: link
  loop:
    - kitty
    - kitten
  loop_control:
    loop_var: file

- name: kitty | link desktop files
  become: true
  file:
    src: "{{ extract_dest }}/share/applications/{{ file }}"
    dest: "/usr/local/share/applications/{{ file }}"
    state: link
  loop:
    - kitty.desktop
    - kitty-open.desktop
  loop_control:
    loop_var: file

- name: kitty | create icons dir
  become: true
  file:
    path: "/usr/local/share/icons/hicolor/256x256/apps"
    state: directory
    mode: "0755"

- name: kitty | link icon
  become: true
  file:
    src: "{{ extract_dest }}/share/icons/hicolor/256x256/apps/kitty.png"
    dest: "/usr/local/share/icons/hicolor/256x256/apps/kitty.png"
    state: link
