#!/bin/sh

connected_displays="$(xrandr | grep " connected " | awk '{ print $1 }')"

echo "$connected_displays" | xargs -L1 -I {} bspc monitor {} -d 1 2 3 4 5 6 7 8

bspc config automatic_scheme alternate >/dev/null 2>&1 &

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config click_to_focus true
bspc config pointer_follows_monitor true

bspc config pointer_modifier Mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -r "*"
bspc config external_rules_command "$HOME/.config/bspwm/external_rules"

###---Autostart---###
"$XDG_CONFIG_HOME/bspwm/autostart.sh" "$1"

# for WebStorm to work correctly
# wmname LG3D
