#!/bin/sh 

# bspc rule -r "*"
$HOME/bin/autostart.sh
###---Autostart---###

# for WebStorm to work correctly
wmname LG3D

bspc monitor HDMI-1 -d 1 2 3 4 5 6
bspc monitor eDP-1 -d 7 8 9 0
bspc wm --reorder-monitors HDMI-1 eDP-1 

bspc config automatic_scheme alternate> /dev/null 2>&1 & 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true

bspc config click_to_focus true

bspc config pointer_modifier Mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a PanGPUI state=floating
