---
- name: Enable deb-src in ubuntu.sources ## so that apt module build-deps works
  when: ansible_distribution == "Ubuntu"
  become: true
  replace:
    path: /etc/apt/sources.list.d/ubuntu.sources
    regexp: "^Types: deb$"
    replace: "Types: deb deb-src"
  notify: Apt update

- name: Install base packages
  become: true
  apt:
    name:
      - nala
      - git
      - curl
      - wget
      - htop
      - vim
      - libsqlite3-dev
      - ssh
      - man-db
      - plocate
      - zsh
      - dash
      - ufw
      - psmisc

- name: Install service DE packages
  become: true
  apt:
    name:
      - dunst
      - pipewire-audio
      - network-manager-gnome

- name: Install pipewire (Debian only)
  when: ansible_distribution == "Debian"
  become: true
  apt:
    name:
      - pipewire-audio

- name: Install DE packages
  become: true
  apt:
    name:
      - xorg
      - xorg-dev
      - i3
      - i3blocks
      - xdotool
      - wmctrl
      - wmname
      - xdo
      - xvfb
      - picom
      - arandr
      - autorandr
      - lxsession
      - lxappearance
      - qt5ct
      - adwaita-qt6
      - fonts-noto
      - fonts-font-awesome
      - fonts-ebgaramond
      - font-manager
      - fonts-noto-color-emoji
      - inputplug
      - xbindkeys
      - pulsemixer
      - pavucontrol
      - pamixer
      - playerctl
      - bluez
      - blueman
      - gnome-keyring
      - xfce4-power-manager
      - mate-system-monitor
      - conky-std
      - udiskie
      - xarchiver
      - ueberzug
      - dmenu
      - rofi
      - feh
      - libimage-exiftool-perl
      - mediainfo
      - unclutter
      - sxhkd
      - xsettingsd

- name: Install applications
  become: true
  apt:
    name:
      - alacritty
      - kitty
      - caja
      - nsxiv
      - evince
      - zathura
      - zathura-djvu
      - flameshot
      - pass
      - timeshift
      - safeeyes
      - xprintidle
      - redshift
      - geoclue-2.0
      - surf
      - libreoffice
      - kazam
      - simplescreenrecorder
      - goldendict
      - qbittorrent
      - webcamoid
      - sonic-visualiser
      - syncthing
      - android-file-transfer
      # - newsboat
      - mpv
      - socat ## needed for mpv socket control
      - mpd
      - mpc
      - ncmpcpp
      - mpdris2
      - lynx
      - firefox

- name: Install CLI utils
  become: true
  apt:
    name:
      - pandoc
      - htop
      - trash-cli
      - xclip
      # - tmux
      - ffmpeg
      - ffmpegthumbnailer
      - imagemagick
      - rsync
      - jq
      - yq
      - tree
      - speedtest-cli
      - colordiff
      - bat
      - ytfzf
      - ripgrep
      - atool
      - unzip
      - zip
      - p7zip
      - moreutils
      - net-tools
      - parallel
      - fdupes
      - libfile-mimeinfo-perl
      - neofetch
      - uglifyjs
      - entr
      - scrot
      - slop
      - powertop
      - brightnessctl
      - urlscan
      - httpie
      - tig
      - zeal
      - shellcheck
      - yad
      - pipx
      - golang
      - timewarrior
      - ncal
      - npm
      - inotify-tools ## recommended by neovim

- name: Install pipx
  include_tasks: tasks/software/build/pipx.yml
  tags:
    - pipx
  vars:
    pipx_args:
      - name: git-filter-repo
      - name: beets
      - name: qtile
      - name: mitmproxy

- name: Install apm packages
  tags:
    - apm
  include_tasks: apm/main.yml
  loop:
    - lazydocker
    - czkawka-cli
    - czkawka-gui
    - dua-cli
    - fnm
    - frece
    - fzf
    - handlr
    - jqp
    - tokei
    - lf
    - yazi
    - fd
    - zoxide
    - bottom
    - onefetch
    - lazygit
    - git-delta
    - diffnav
    - rclone
    - pacstall
    - yt-dlp
    - ctpv ## image previewer for lf
    - kitty
    - windowlist
    - supersonic
    - devtoys
    - devtoys.cli
    - wmutils
    - i3lock-color ## dependency of betterlockscreen
    - betterlockscreen
    - xkblayout-state
    - volctl
    - clipmenu
    - dragon-drop
    - libinput-gestures
    - tealdeer
    - nerd-fonts-jetbrains-mono
    - nerd-fonts-fira-code
    - nerd-fonts-fira-mono
    - aporetic-fonts
    - simp1e-gruvbox-dark-cursor-theme
    - keyd
    - auto-cpufreq
    - localsend
    - gh-dash

- name: Install applications | pacstall
  become: true
  failed_when: false
  pacstall:
    name:
      - vscodium-deb
      - brave-browser-deb
      - spotify-client-deb
      - telegram-bin

- name: Install work applications | pacstall
  when: ansible_distribution == "Ubuntu"
  become: true
  failed_when: false
  pacstall:
    name:
      - slack-deb
      - google-chrome-deb
      - github-cli-bin
