- name: Install base packages
  become: true
  apt:
    name:
      - nala
      - git
      - curl
      - wget
      - htop
      - vim
      - libsqlite3-dev
      - ssh
      - man-db
      - plocate
      - zsh
      - dash
      - ufw
      - psmisc

- name: Install DE packages
  become: true
  apt:
    name:
      - xorg
      - xdotool
      - wmctrl
      - wmname
      - xdo
      - xvfb
      - lightdm
      - lightdm-gtk-greeter
      - dunst
      - picom
      - arandr
      - autorandr
      - lxsession
      - lxappearance
      - papirus-icon-theme
      - qt5ct
      - adwaita-qt6
      - fonts-noto
      - fonts-font-awesome
      - fonts-ebgaramond
      - font-manager
      - fonts-noto-color-emoji
      - inputplug
      - xbindkeys
      - pipewire-audio
      - pulsemixer
      - pavucontrol
      - pamixer
      - playerctl
      - bluez
      - blueman
      - budgie-network-manager-applet
      - gnome-keyring
      - xfce4-power-manager
      - mate-system-monitor
      - conky
      - udiskie
      - xarchiver
      - ueberzug
      - dmenu
      - rofi
      - feh
      - libimage-exiftool-perl
      - mediainfo
      - unclutter

- name: pacstall | install DE packages
  pacstall:
    name:
      - wmutils
      - awesome-git
      - betterlockscreen
      # - arc-gruvbox-gtk-theme-git
      - simp1e-gruvbox-dark-cursor-theme-git
      - nerd-fonts-jetbrains-mono
      - nerd-fonts-fira-code
      - nerd-fonts-fira-mono
      - keyd
      - xkblayout-state-git
      - volctl

- name: Install applications
  become: true
  apt:
    name:
      - alacritty
      - kitty
      - caja
      - nsxiv
      - evince
      - zathura
      - zathura-djvu
      - flameshot
      - pass
      - timeshift
      - safeeyes
      - xprintidle
      - redshift
      - geoclue-2.0
      - surf
      - libreoffice
      - kazam
      - simplescreenrecorder
      - goldendict
      - qbittorrent
      - webcamoid
      - sonic-visualiser
      - syncthing
      - android-file-transfer
      # - newsboat
      - mpv
      - mpd
      - mpc
      - ncmpcpp
      - mpdris2
      - lynx

- name: Install applications | pacstall
  become: true
  pacstall:
    name:
      # - selectdefaultapplication
      # - rofi-calc
      - clipmenu-git
      - libinput-gestures
      - auto-cpufreq
      - czkawka-gui-bin
      - dragon-drop
      - vscodium-deb
      - firefox-bin
      - brave-browser-deb
      # - protonvpn-gui
      - telegram-bin
      - freetube-deb
    # - spotify-client-deb
    # - activitywatch-bin
    # - monero-gui
    # - skypeforlinux-stable-bin
    # - slack-deb
    # - zoom-deb
    # - google-chrome-deb

- name: Install CLI utils
  become: true
  apt:
    name:
      - pandoc
      - htop
      - trash-cli
      - xclip
      # - tmux
      - ffmpeg
      - ffmpegthumbnailer
      - imagemagick
      - rsync
      - jq
      - tree
      - speedtest-cli
      - colordiff
      - bat
      - yt-dlp
      - ytfzf
      - ripgrep
      - thefuck
      - atool
      - unzip
      - zip
      - p7zip
      - moreutils
      - net-tools
      - parallel
      - fdupes
      - libfile-mimeinfo-perl
      - neofetch
      - uglifyjs
      - entr
      - scrot
      - slop
      - powertop
      - brightnessctl
      - urlscan
      - httpie
      - tig
      - zeal
      - tealdeer
      - shellcheck
      - yad
      - pipx

- name: Install rclone from url
  vars:
    - version: 1.69.0
  become: true
  apt:
    deb:
      https://downloads.rclone.org/v{{ version }}/rclone-v{{ version
      }}-linux-amd64.deb

- name: pipx packages
  become: true
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
  tags:
    - pipx
  vars:
    pipx_packages:
      - git-filter-repo
  community.general.pipx:
    name: "{{ item }}"
  with_items: "{{ pipx_packages }}"
