- name: install pacstall
  tags:
    - pacstall
  vars:
    version: 6.1.0
    url:
      https://github.com/pacstall/pacstall/releases/download/{{ version
      }}/pacstall_{{ version }}-pacstall1_all.deb
    sha: sha256:3c8436eccaa584fd19884be3ae0297a80d8d884949654d9a365087f9b6f8c3b5

  block:
    - name: pacstall | get installed version
      command: pacstall -V
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: pacstall_installed

    - name: pacstall | parse installed version
      set_fact:
        installed_version: "{{ pacstall_installed.stdout.split(' ')[0] }}"
      when: pacstall_installed.stdout | length > 0

    - name: pacstall | get deb file
      when: installed_version is not defined or installed_version != version
      get_url:
        url: "{{ url }}"
        dest: /tmp/pacstall-{{ version }}.deb
        checksum: "{{ sha }}"

    - name: pacstall | force install specific version
      become: true
      when: installed_version is not defined or installed_version != version
      command: dpkg -i /tmp/pacstall-{{ version }}.deb

    - name: pacstall | add personal repo
      become: true
      lineinfile:
        path: /usr/share/pacstall/repo/pacstallrepo
        line: https://raw.githubusercontent.com/sarmong/pacstall-sarmong/master
