#!/bin/sh

lfcd() {
  # This part will change a directory in a shell once you quit lf
  tmp="$(mktemp)"
  "$XDG_CONFIG_HOME"/lf/lf-with-preview -last-dir-path="$tmp" "$@"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp" >/dev/null
    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir" || exit
  fi
}
