#!/bin/sh

# File preview handler for lf.

file=$1
w=$2
h=$3
x=$4
y=$5

set -C -f
IFS="$(printf '%b_' '\n')"
IFS="${IFS%_}"

image() {
  if [ "$TERM" = "xterm-kitty" ]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty

  elif [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
    printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$x" "$y" "$(("$w" - 1))" "$(("$h" - 1))" "$1" >"$FIFO_UEBERZUG"
  else
    mediainfo "$1"
  fi
}

# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

case "$(file --dereference --brief --mime-type -- "$file")" in
  *djvu*)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    [ ! -f "$CACHE" ] && ddjvu -quality=90 -page=1 <"$1" >"$CACHE"
    image "$CACHE"
    ;;
  image/*) image "$1" ;;
  text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
  text/troff) man ./ "$1" | col -b ;;
  text/* | */xml | application/json) bat --terminal-width "$4" -f "$1" ;;
  application/zip | application/gzip) atool --list -- "$1" ;;
  audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
  video/*)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
    image "$CACHE"
    ;;
  */pdf)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    image "$CACHE.jpg"
    ;;
  *opendocument*) odt2txt "$1" ;;
  application/pgp-encrypted) gpg -d -- "$1" ;;
  application/vnd.openxmlformats-officedocument.wordprocessingml.document | application/msword | application/vnd.ms-excel)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    if [ ! -f "$CACHE" ]; then
      libreoffice --convert-to jpg "$1" --outdir "${XDG_CACHE_HOME:-$HOME/.cache}/lf/"
      filename=$(basename "$1")
      mv "${XDG_CACHE_HOME:-$HOME/.cache}/lf/${filename%.*}.jpg" "$CACHE"
    fi
    image "$CACHE"
    ;;
esac

exit 1
