[ids]
*
# This disables keyd for custom keyboards
# see `lsusb`
# Wired Lily
-1d50:615e
# Wireless (probably not needed)
-0:0

[main]
# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock

# sysrq is prtsc
sysrq = rightalt
# compose is menu
compose = rightalt
rightalt = layer(alt)

alt = layer(meta)
meta = layer(alt)

# Preserve right ctrl so XKB can use it (e.g. as compose key)
rightcontrol = rightcontrol

[meta]
end = playpause
home = previoussong
insert = nextsong

# @TODO try new kbd layouts instead of xkbmap
# [ru]
# include layouts/ru
#
# ctrl+ = layer(main)
#
