#!/bin/sh

## Checks if command exists
exists() {
  type "$1" &>/dev/null
  return "$?"
}

[ -f "$HOME/.config/zsh/xdg-cleanup" ] && . "$HOME/.config/zsh/xdg-cleanup"

export TIMEWARRIORDB="$XDG_NC_DIR/Documents/timewarrior"

export PATH="$XDG_DATA_HOME/nvvm/bin:$PATH:"
export PATH="$XDG_BIN_DIR:$XDG_BIN_DIR/launchers:$XDG_BIN_DIR/wrappers:$PATH"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=100000
export HISTFILESIZE=1000000
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER=firefox
export PAGER=less
export QT_QPA_PLATFORMTHEME="qt5ct" # required by qt5ct
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket" # started by ssh-agent.service, instead of eval $(ssh-agent -s)

# Fixes issues with Java application(Webstorm) in tiling WM
export _JAVA_AWT_WM_NONREPARENTING=1

## Set custom MANPAGER
export MANWIDTH="80"
# fixes formatting issues
export MANROFFOPT="-c"

[ -f "$HOME/.config/zsh/zsh-local" ] && . "$HOME/.config/zsh/zsh-local"
