#!/bin/sh

## Checks if command exists
exists() {
  type "$1" &>/dev/null
  return "$?"
}

[ -f "$HOME/.config/zsh/xdg-cleanup" ] && . "$HOME/.config/zsh/xdg-cleanup"

export TIMEWARRIORDB="$XDG_NC_DIR/Documents/timewarrior"

export PATH="$PATH:$XDG_DATA_HOME/bob/nvim-bin"
export PATH="$PATH:$XDG_DATA_HOME/nvvm/bin"
export PATH="$XDG_BIN_DIR:$XDG_BIN_DIR/launchers:$XDG_BIN_DIR/wrappers:$PATH"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=100000
export HISTFILESIZE=1000000
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER=firefox
export PAGER=less
export QT_QPA_PLATFORMTHEME="qt5ct" # required by qt5ct

# Fixes issues with Java application(Webstorm) in tiling WM
export _JAVA_AWT_WM_NONREPARENTING=1

## Set custom MANPAGER
export MANWIDTH="80"
# fixes formatting issues
export MANROFFOPT="-c"
