#!/usr/bin/env zsh

## Checks if command exists
function exists() {
  type "$1" &>/dev/null
  return "$?"
}

# Function to source files if they exist
# Set second argument to true to only source the file in interactive shell
function zsh_add_file() {
  case $1 in
    /*) [ -f "$1" ] && source "$1" ;;
    *) [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1" ;;
  esac
}

function zsh_add_plugin() {
  [[ $- != *i* ]] && return

  PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
  FILE_NAME="${2:-$PLUGIN_NAME}"
  if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then
    # For plugins
    zsh_add_file "plugins/$PLUGIN_NAME/$FILE_NAME.plugin.zsh" ||
      zsh_add_file "plugins/$PLUGIN_NAME/$FILE_NAME.zsh"
  else
    git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
  fi
}

function zsh_add_completion() {
  PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
  if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then

    # For completions
    completion_file_path=$(ls $ZDOTDIR/plugins/$PLUGIN_NAME/_*)
    fpath+="$(dirname "${completion_file_path}")"
    zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh"
  else
    git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
    fpath+=$(ls $ZDOTDIR/plugins/$PLUGIN_NAME/_*)
    [ -f $ZDOTDIR/.zccompdump ] && $ZDOTDIR/.zccompdump
  fi
  completion_file="$(basename "${completion_file_path}")"
  [ "$2" = true ] && compinit "${completion_file:1}"
}
