#!/usr/bin/env zsh

## Checks if command exists
function exists() {
  type "$1" &>/dev/null
  return "$?"
}

# Function to source files if they exist
# Set second argument to true to only source the file in interactive shell
function zsh_add_file() {
  case $1 in
    /*) [ -f "$1" ] && source "$1" ;;
    *) [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1" ;;
  esac
}

function zsh_download_plugin_if_needed() {
  REPO="$1"
  PLUGIN_NAME="$2"

  zdotdir_src=$(realpath --relative-to="$XDG_DOTFILES_DIR" $ZDOTDIR)
  plugins_dir="$zdotdir_src/plugins"
  [ ! -d "$plugins_dir" ] && mkdir -p "$plugins_dir"

  if [ ! -d "$plugins_dir/$PLUGIN_NAME" ]; then
    git submodule add --name "$PLUGIN_NAME" -- "https://github.com/$REPO.git" "$plugins_dir/$PLUGIN_NAME"
  fi
}

function zsh_add_plugin() {
  [[ $- != *i* ]] && return

  REPO="$1"
  PLUGIN_NAME=$(echo $REPO | cut -d "/" -f 2)
  FILE_NAME="${2:-$PLUGIN_NAME}"

  zsh_download_plugin_if_needed "$REPO" "$PLUGIN_NAME"

  zsh_add_file "plugins/$PLUGIN_NAME/$FILE_NAME.plugin.zsh" ||
    zsh_add_file "plugins/$PLUGIN_NAME/$FILE_NAME.zsh"
}

function zsh_add_completion() {
  PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
  if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then

    # For completions
    completion_file_path=$(ls $ZDOTDIR/plugins/$PLUGIN_NAME/_*)
    fpath+="$(dirname "${completion_file_path}")"
    zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh"
  else
    git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
    fpath+=$(ls $ZDOTDIR/plugins/$PLUGIN_NAME/_*)
    [ -f $ZDOTDIR/.zccompdump ] && $ZDOTDIR/.zccompdump
  fi
  completion_file="$(basename "${completion_file_path}")"
  [ "$2" = true ] && compinit "${completion_file:1}"
}
