Net/ThemeName "Yaru-bark"
Net/IconThemeName "Papirus-Light"
Net/EnableEventSounds 1
Gtk/CursorThemeName "breeze_cursors"
Gtk/FontName "Sans 10"
Gtk/ColorScheme ""
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintmedium"
