- name: Bootstrap main system
  hosts: localhost
  tasks:
    - name: Load xdg vars
      tags: always
      include_vars:
        file: vars/xdg.yml

    - name: Extend ansible_env
      set_fact:
        ansible_env: "{{ ansible_env | combine(xdg) }}"

    - name: dotfiles
      tags: dotfiles
      block:
        - import_tasks: tasks/dotfiles/main.yml
        - import_tasks: tasks/dotfiles/tmux-plugins.yml

    - name: software
      tags: software
      block:
        - import_tasks: tasks/software/build/rust.yml
        - import_tasks: tasks/software/ppa.yml
        - import_tasks: tasks/software/main.yml
        - import_tasks: tasks/software/build/main.yml

    - name: configuration
      tags: conf
      block:
        - import_tasks: tasks/configure/audio.yml
        - import_tasks: tasks/configure/cron.yml
        - import_tasks: tasks/configure/geoclue.yml
        - import_tasks: tasks/configure/keyd.yml
        - import_tasks: tasks/configure/lightdm.yml
        - import_tasks: tasks/configure/suspend.yml
        - import_tasks: tasks/configure/touchpad.yml
        - import_tasks: tasks/configure/ufw.yml
        - import_tasks: tasks/configure/ui.yml
        - import_tasks: tasks/configure/sudoers.yml
        - import_tasks: tasks/configure/misc.yml
        - import_tasks: tasks/configure/network.yml
        - import_tasks: tasks/configure/gtk.yml
