- name: Localhost playbook
  ansible.builtin.import_playbook: localhost.yml

- name: VPS playbook
  ansible.builtin.import_playbook: server.yml

- name: Media playbook
  ansible.builtin.import_playbook: media.yml
