- name: Bootstrap media system
  hosts: quad
  tasks:
    - name: Install selected packages
      tags:
        - apm
      include_tasks: tasks/software/apm/main.yml
      loop:
        - dua-cli

    - name: Install packages
      become: true
      apt:
        name:
          - nala
          - git
          - curl
          - wget
          - htop
          - vim
          - ssh
          - man-db
          - plocate
          - zsh
          - dash
          - ufw
          - lf
          - tmux
          - zoxide
          - rsync
          - jq
          - fzf

    - name: Install media packages
      become: true
      apt:
        name:
          - libinput10
          - pipewire-audio
          - pulsemixer
          - xorg
          - unclutter
          - kodi
          - mpv
          - socat ## needed for mpv socket control
          - bluez
          - blueman

    - name: Load xdg variables (with new loaded ansible_env)
      tags: always
      include_vars:
        file: vars/xdg.yml

    - name: Extend ansible_env
      set_fact:
        ansible_env: "{{ ansible_env | combine(xdg) }}"

    - import_tasks: tasks/server/dotfiles.yml

    - name: Copy bt-connect.sh
      become: true
      copy:
        src: tasks/media/files/bt-connect.sh
        dest: "/usr/local/bin/bt-connect"
        mode: "0755"

    - name: Copy bt-autoconnect.service
      become: true
      copy:
        src: tasks/media/files/bt-autoconnect.service
        dest: "/etc/systemd/system/bt-autoconnect.service"
        mode: "0644"

    - name: services
      become: true
      systemd_service:
        name: "{{ item }}"
        enabled: true
      loop:
        - bluetooth
        - bt-autoconnect

    - name: Change user shell
      become: true
      user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/zsh
        groups: input,kodi
        append: true

    # - import_tasks: tasks/configure/keyd.yml
    - import_tasks: tasks/configure/ufw.yml

    - import_tasks: tasks/media/navidrome.yml
    - import_tasks: tasks/media/qbittorrent.yml
    - import_tasks: tasks/media/beets.yml
    - import_tasks: tasks/media/kodi-standalone.yml
    - import_tasks: tasks/media/lighttpd.yml
