#!/usr/bin/env bash

eval $(thefuck --alias)

# Brew commands
alias binstall="brew install"
alias cinstall="brew cask install"
alias bsearch="brew search"
alias binfo="brew info"

# Apt commands
alias update="sudo apt update && sudo apt upgrade && brew update && brew upgrade"
alias aptinst="sudo apt install"
alias aptsearch="apt search"
alias aptremove="sudo apt remove"

# Abbreviations
alias r="ranger"
alias lf="lfcd"
alias ka="killall"
alias g="git"
alias gs="git status"
alias gcob='git branch | fzf | xargs git checkout'

[ $(uname) == 'Darwin' ] && alias ls="gls -hGF --color=auto --group-directories-first" || alias ls="ls -hGF --color=auto --group-directories-first"
alias la="ls -A"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias mv="mv -i"
alias rm="rm -i"
alias mkd="mkdir -pv"
alias untar="tar -zxvf"
alias sha="shasum -a 256" # check the checksum of a file

mcd() {
	mkdir -pv "$1"
	cd "$1"
}

alias open="xdg-open"
alias o="xdg-open"
alias copy="xclip -sel clipboard"

alias v="nvim"
alias fo="fzf | xargs xdg-open"

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcuts
alias pr="cd ~/Documents/Tech/Projects"
alias dox="cd ~/Documents"
alias dls="cd ~/Downloads"

alias yt="yt-dlp"          # Download video
alias yta="yt-dlp -f 'ba'" # Download audio
play() {
	mpv "$1" &
	disown
}

# Might be useful
alias weather="curl wttr.in"
alias myip="curl ipinfo.io/ip"
alias week='date +%V'

###
# macOs
###

alias yabairestart='launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"'

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
