#!/bin/bash

exists thefuck && eval "$(thefuck --alias)"

# Brew commands
alias binstall="brew install"
alias cinstall="brew cask install"
alias bsearch="brew search"
alias binfo="brew info"

# Apt commands
alias update="sudo apt update && sudo apt upgrade && brew update && brew upgrade"
alias aptinst="sudo apt install"
alias aptsearch="apt search"
alias aptremove="sudo apt remove"

alias p="sudo pacman"

# Abbreviations
[ -f "$XDG_CONFIG_HOME/lf/lfcd" ] && . "$XDG_CONFIG_HOME/lf/lfcd"
alias lf="lfcd"
alias ka="killall"
alias g="git"
alias gs="git status"
alias gcob='git branch | fzf | xargs git checkout'
alias s="systemctl"
alias ss="sudo systemctl"
alias j="journalctl"

[ "$(uname)" = 'Darwin' ] && alias ls="gls -hGF --color=auto --group-directories-first" || alias ls="ls -hGF --color=auto --group-directories-first"
alias la="ls -A"
alias ll="ls -Al"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias mv="mv -i"
alias rm="rm -I"
alias t="trash"
alias mkd="mkdir -pv"
alias untar="tar -zxvf"
alias sha="shasum -a 256" # check the checksum of a file
alias diff="colordiff"
pdfman() {
  man -Tpdf "$1" | zathura -
  # man -t "$1" | ps2pdf - | zathura -
}

alias open="xdg-open"
alias o="xdg-open"
alias mtype="file -b --mime-type"
alias copy="xclip -sel clipboard"

alias v="nvim"
alias fo="fzf | xargs xdg-open"
alias nb="newsboat"

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias yta="yt-dlp --embed-metadata -f 'ba'" # Download audio
play() {
  mpv "$1" &
  disown
}

# Might be useful
alias weather="curl wttr.in"
alias moon="curl wttr.in/moon"
alias myip="curl ipinfo.io/ip"
alias week='date +%V'

mcd() {
  mkdir -pv "$@" && cd "${@:$#}" || exit
}

takearchive() {
  local data thedir
  data="$(mktemp)"
  curl -L "$1" >"$data"
  tar xf "$data"
  thedir="$(tar tf "$data" | head -n 1)"
  rm -f "$data"
  cd "$thedir" || exit
}

takegit() {
  git clone "$1"
  cd "$(basename "${1%%.git}")" || exit
}

take() {
  if [[ $1 =~ ^(https?|ftp).*\.tar\.(gz|bz2|xz)$ ]]; then
    takearchive "$1"
  elif [[ $1 =~ ^([A-Za-z0-9]\+@|https?|git|ssh|ftps?|rsync).*\.git/?$ ]]; then
    takegit "$1"
  else
    mcd "$@"
  fi
}

###
# macOs
###

alias yabairestart='launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"'

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
