#!/bin/sh

## Checks if command exists
exists() {
  type "$1" &>/dev/null
  return "$?"
}

[ -f "$HOME/.config/zsh/xdg-cleanup" ] && . "$HOME/.config/zsh/xdg-cleanup"

export TIMEWARRIORDB="$XDG_NC_DIR/Documents/timewarrior"

export PATH="$PATH:$XDG_DATA_HOME/bob/nvim-bin"
export PATH="$PATH:$XDG_DATA_HOME/nvvm/bin"
export PATH="$XDG_BIN_DIR:$XDG_BIN_DIR/launchers:$XDG_BIN_DIR/wrappers:$PATH"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=100000
export HISTFILESIZE=1000000
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER=firefox
export PAGER=less
export QT_QPA_PLATFORMTHEME="qt5ct" # required by qt5ct

# Fixes issues with Java application(Webstorm) in tiling WM
export _JAVA_AWT_WM_NONREPARENTING=1

## Set custom MANPAGER
export MANWIDTH="80"
# fixes formatting issues
export MANROFFOPT="-c"

## ==================== ##
## Programming settings ##
## ==================== ##

# Node settings
# ============

[ -d "$XDG_DATA_HOME/npm/bin" ] && export PATH="$PATH:$XDG_DATA_HOME/npm/bin"

## Might need for Ubuntu
# export NVM_DIR="$XDG_CONFIG_HOME/nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

exists fnm && eval "$(fnm env --use-on-cd --version-file-strategy recursive)"

if exists mkcert; then
  export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
else
  unset NODE_EXTRA_CA_CERTS
fi

export BUN_INSTALL="$XDG_DATA_HOME/bun"
if [ -d "$BUN_INSTALL" ]; then
  export PATH="$BUN_INSTALL/bin:$PATH"
  # bun completions
  [ -s "$BUN_INSTALL/_bun" ] && . "$BUN_INSTALL/_bun"
fi

# Golang
# ========

export GOPATH="$XDG_DATA_HOME/go"
export PATH="$PATH:$GOPATH/bin"

# Rust
# ===============

export RUSTUP_HOME="$XDG_CONFIG_HOME"/rust/rustup
export CARGO_HOME="$XDG_CONFIG_HOME"/rust/cargo

export PATH="$HOME/.cargo/bin:$PATH"
[ -f "$XDG_CONFIG_HOME/rust/cargo/env" ] && . "$XDG_CONFIG_HOME/rust/cargo/env"

# Scala
if [ -d "$XDG_DATA_HOME"/coursier ]; then
  export PATH="$PATH:$XDG_DATA_HOME/coursier/bin"
fi

if [ "$(uname)" != "Darwin" ] && [ -s "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  export PATH="$PATH":/home/linuxbrew/.linuxbrew/bin
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
